name: eatify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter  

  easy_localization: ^3.0.8

 # UI
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  flutter_riverpod: ^2.5.1   # State Management
  supabase_flutter: ^2.5.6   # Supabase
  # Location & Maps
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  # Utilities
  uuid: ^4.4.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  intl: ^0.20.2
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/translations/en.json
    - assets/translations/ar.json